### ISSUE TITLE
Print receipt feature

### ISSUE THREAD

**Issue by damn-dvlpr** [damn-dvlpr/loanApp#4]
Print receipt feature to be added which prints the table shown in Customer details.

**Comment by gaurav219** [comment]
Hey!!
Do you mean a PDF document which'll show the table, right?

**Comment by karmanya007** [comment]
I would like to help.Is anyone working on this?

**Comment by damn-dvlpr** [comment]
@gaurav219 yes, that will suffice.

**Comment by karmanya007** [comment]
![table](https://user-images.githubusercontent.com/24437967/95063120-8f065380-071b-11eb-807b-6bc7dc982e00.jpg)
This table?

**Comment by damn-dvlpr** [comment]
Yes.

**Comment by karmanya007** [comment]
![table2](https://user-images.githubusercontent.com/24437967/95063329-d42a8580-071b-11eb-8d42-5265f86e4b82.jpg)
Or this one?

**Comment by karmanya007** [comment]
After it has been marked delivered?

**Comment by damn-dvlpr** [comment]
Both have seldom differences, as the receipt is for the customer, it should contain the date of delivery and the total amount submitted i.e. amount given+interest. Hence first one would do, with a added field of delivery date.

**Comment by karmanya007** [comment]
Okay

**Comment by IndyDevGuy** [comment]
Would it be okay to use wkhtmltopdf? It is a PHP extension, I have used it many times before and it works great. More info here: https://wkhtmltopdf.org

**Comment by karmanya007** [comment]
Bro I am nearly done with this.

**Comment by IndyDevGuy** [comment]
> Bro I am nearly done with this.

Okay no problem!

**Comment by karmanya007** [comment]
![1](https://user-images.githubusercontent.com/24437967/95105081-46b75780-0754-11eb-92e8-92e43761dd82.jpg)
![2](https://user-images.githubusercontent.com/24437967/95105093-49b24800-0754-11eb-8516-da01d4c25ced.jpg)
![3](https://user-images.githubusercontent.com/24437967/95105103-4cad3880-0754-11eb-8e3b-bb010d049d3b.jpg)
[Reciept.pdf](https://github.com/damn-dvlpr/loanApp/files/5328621/Reciept.pdf)

Is this fine??

**Comment by karmanya007** [comment]
![4](https://user-images.githubusercontent.com/24437967/95106258-ec1efb00-0755-11eb-848b-9cf2f94ffb00.jpg)

Also removed the metal which doesn't exist.

**Comment by damn-dvlpr** [comment]
This looks great! btw which library have you used for this? please open a PR so I can view the changes.

**Comment by karmanya007** [comment]
No library. Just simple ol' window.print() 😉

**Comment by damn-dvlpr** [comment]
A sophisticated library would have been preferred, but nevertheless, I would merge this. If some problem persists, would revert it back as we don't have tests, so keep an eye if you're in for hacktoberfest.

**Comment by damn-dvlpr** [comment]
Solved by PR #6
