### ISSUE TITLE
Restructuring the routes

### ISSUE THREAD

**Issue by damn-dvlpr** [damn-dvlpr/loanApp#7]
Currently the "app.js" file is too big, we can refactor it by moving all the routes to a different file and directly calling them in the app.js by app.routes() function.
Further refactoring suggestions are welcome.

**Comment by karmanya007** [comment]
Could refactor the code into a MVC structure.
The Views already exists. I'll create the models (MongoDB models), the Controllers(The callback functions of the the routes) and the routes.
How is this idea??

**Comment by damn-dvlpr** [comment]
Yes, that's exactly what is needed.

**Comment by damn-dvlpr** [comment]
Just one suggestion, don't just delete the whole code and paste it again with minor changes as it makes file review difficult, what i mean is, do the changes in the main file only, so that git can track exactly the lines you're changing, you can check your preview PR and the files changes, it shows a bunch of deleted lines and same lines added again with minor changes #6 .

**Comment by karmanya007** [comment]
I think that is due to the prettier extension. It spaced out the code so it shows up as new code. Now that the files that i have worked on are already prettified,  the deleted line won't show up.

**Comment by karmanya007** [comment]
Bro, do you really need the logging to a file. You can just use morgan as a middleware.

**Comment by karmanya007** [comment]
Done!! 😊

**Comment by damn-dvlpr** [comment]
I was thinking to move the 'log' file to .gitignore file, as it's not needed on github.

**Comment by karmanya007** [comment]
Make a folder called config in the base directory and put a file called config.env with the following :
NODE_ENV=development
PORT=3000
DATABASE_LOCAL=mongodb://localhost:27017/shop
DATABASE_CLOUD=
DATABASE_PASSWORD=

**Comment by damn-dvlpr** [comment]
That's some really great work! Merged PR.
